### ISSUE TITLE
Add compatibility for Cinnamon 3.6 and fixes for StarkMenu

### ISSUE THREAD

**Issue by AndromedaRecall** [B00merang-Project/Windows-7-Decorations#1] opened 2017-12-07 20:46 UTC
Hi!

Since this is related to the Windows.Se7en.R5 which you've done please could you update the Windows 7 theme to make it fully compatible with Cinnamon 3.6 and StarkMenu so it does NOT show a grey start menu but in fact the Windows 7 theme start menu. Please do the fixes for StarkMenu and update your website https://b00merang.weebly.com/redmond-collection.html 

Also note that your Vista theme isn't compatible also with the latest StarkMenu and the menu doesn't look right please fix if you can.

**Comment by dominichayesferen** [comment] 2017-12-08 07:52
Duplicate of same issue + wrong Repo

**Closed as completed** 2017-12-08 07:51 UTC
